### ISSUE TITLE
dita-ot 3x support

### ISSUE THREAD

**Issue by pimbekker** [oxygenxml/dita-ot-3x-plugin#2]
After installing it puts the dita-ot 3 in my user folder, not on the same level as the dita-ot 2x in the framework folder inside the Oxygen installation

**Comment by raducoravu** [comment]
Yes, this works as designed. Usually an Oxygen installation on Windows is made in the Program Files folder anyway so a plugin in Oxygen does not usually have rights to copy content to the Program Files folder anyway.
So indeed the DITA OT 3.x remains and is used directly from the add-on which is unpacked and installed in the user's local settings folder.
